name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger only when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Step 3: Get current date and commit hash for versioning
    - name: Generate version
      id: version
      run: |
        DATE=$(date +%Y.%m.%d)
        HASH=$(git rev-parse --short HEAD)
        VERSION="$DATE-$HASH"
        echo "::set-output name=VERSION::$VERSION"

    # Step 3: Build the Docker image
    - name: Build Docker image
      working-directory: BirthdayBox
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/jjppta-birthdaybox:${{ steps.version.outputs.VERSION }} .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/jjppta-birthdaybox:${{ steps.version.outputs.VERSION }}